# USE OF STAR OPERATOR IN PYTHON

# THE STAR OPERATOR IS USED TO MULTIPLY THE TUPLES WITH THE INTEGRAL QUANTITY MENTIONED USING STAR OPERATOR
# The number put must be an integer

tuple1 = (1,2,3,4,5)
mult = tuple1 * 8

print(mult)