# Write a program to count number of vowels using set in given string.

def vowelNum(v_string):
    
    vowel = set("aeiouAEIOU")       # all vowels are considered in both upper and lower cases
    
    count = sum(1 for char in v_string if char in vowel)
    #   adds all the '1's generated by the generator function
    #   everytime the generator condition is true -- it will return 1

    return count

value = input("Enter the string value: ")
ans = vowelNum(value)
print("Number of vowels : ",ans)